<?php

namespace App\Utils;

enum EquipmentEnum: string
{
    case HEAVY_VEHICLE_TYPE = 'HEAVY_VEHICLE_TYPE';
    case HEAVY_EQUIPMENT_TYPE = 'HEAVY_EQUIPMENT_TYPE';
    case LIGHT_VEHICLE_TYPE = 'LIGHT_VEHICLE_TYPE';
    case MEDIUM_VEHICLE_TYPE = 'MEDIUM_VEHICLE_TYPE';
}
