<?php

namespace Tests\Models;

use App\Models\Log;
use Illuminate\Support\Facades\DB;
use Tests\TestCase;

class LogTest extends TestCase
{
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        DB::delete("DELETE FROM logs");
    }

    public function testCreate()
    {
        $data = [
            'highlight' => 'pmcow.central: ',
            'event' => 'pmcow.central post an actual highlight',
            'route_name' => 'logs',
            'url' => 'http://127.0.0.1:8000/logs',
            'user_id' => 'f216658e-4da9-418a-b601-bac98a0bd3bf'
        ];
        $logged = Log::factory(3)->create($data);
        foreach ($logged as $log) {
            self::assertSame($data['highlight'], $log->highlight);
            self::assertSame($data['route_name'], $log->route_name);
            self::assertSame($data['url'], $log->url);
            self::assertSame($data['event'], $log->event);
            self::assertSame($data['user_id'], $log->user_id);
        }
    }
}
